{% set name = "spyder-kernels" %}
{% set version = "1.3.2" %}
{% set hash_type = "sha256" %}
{% set hash = "ccd04b6c166150eac40ce91abd350d0ffe4e559b918ddf0cf138deb3917941d2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  {{ hash_type }}: {{ hash }}

build:
  number: 0
  script: {{PYTHON}} setup.py install --single-version-externally-managed --record record.txt

requirements:
  host:
    - python
    - setuptools

  run:
    - python
    - ipykernel
    - cloudpickle

test:
  imports:
    - spyder_kernels

about:
  home: https://github.com/spyder-ide/spyder-kernels
  license: MIT
  license_family: MIT
  summary: 'Jupyter kernels for the Spyder console'

  description: |
    Package that provides the kernels used by Spyder on its IPython console.
    It has as dependencies ipykernel and cloudpickle.
  dev_url: https://github.com/spyder-ide/spyder-kernels/tree/0.x

extra:
  recipe-maintainers:
    - ccordoba12
    - dalthviz
