{% set name = "spyder-kernels" %}
{% set version = "1.0.1" %}
{% set hash_type = "sha256" %}
{% set hash = "ce4950684a3b82cd995700e2623c8749d1194823f990d6ed24711e7db4cf202a" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  {{ hash_type }}: {{ hash }}

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - python
    - setuptools

  run:
    - python
    - ipykernel
    - cloudpickle

test:
  imports:
    - spyder_kernels

about:
  home: https://github.com/spyder-ide/spyder-kernels
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'Jupyter kernels for the Spyder console'

  description: |
    Package that provides the kernels used by Spyder on its IPython console.
    It has as dependencies ipykernel and cloudpickle.
  dev_url: https://github.com/spyder-ide/spyder-kernels/tree/0.x

extra:
  recipe-maintainers:
    - ccordoba12
    - dalthviz
