{% set name = "spyder-kernels" %}
{% set version = "0.2.4" %}
{% set hash_type = "sha256" %}
{% set hash = "d5bfc5fdbc98c8bef7910ac4a28638272179c9077a45e4b9b820ba87a916b18a" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  {{ hash_type }}: {{ hash }}

build:
  noarch: python
  number: 1
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  host:
    - pip
    - python
    - setuptools

  run:
    - python
    - ipykernel
    - cloudpickle

test:
  imports:
    - spyder_kernels

about:
  home: https://github.com/spyder-ide/spyder-kernels
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'Jupyter kernels for the Spyder console'

  description: |
    Package that provides the kernels used by Spyder on its IPython console.
    It has as dependencies ipykernel and cloudpickle.
  dev_url: https://github.com/spyder-ide/spyder-kernels/tree/0.x

extra:
  recipe-maintainers:
    - ccordoba12
    - dalthviz
