# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.
# -*- mode: yaml -*-

language: generic

os: osx
osx_image: xcode9.4


env:
  matrix:
    - CONFIG=osx_python2.7
    - CONFIG=osx_python3.6
    - CONFIG=osx_python3.7

  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "na+VvwQxQF8Ah8bvRTE/9kAr5gtoXMF0fCHbhE8HUwTQdBE/skJSe171dsiVIii/d/wr81WJiJ5h3zdlHAZn7k9G8QYrljsuNx0maZPEU3QF02tp6R6f4tGUoi0ENj7i47ZoNTFWAFmFqPN9lWDpcFJ3T7+R2Da/yQpvrIffHnRvwdv23/NsopoGTUQ2fXJVK1jbP3ZRv0SI90LLRZzlT50P31FvTtTWAImRp00uhuo8brmklySUi/yH92yo3S28jiZ1lkvFucTZ/tgQ/Yb8TUZXrKv7ptNQINDYt4oaPc9TTtzEURyJz+hfmEEfuThAJaGgp+vup+3HdCpJNtP/VeV5nFD3MT7anfzm17WlAc/GJ37qmtFwr90PuHrXF3I+YGEi7Ohwqevbv5DFdBBZfi6fl1jQSVDllTx/90eF4wrarcHebpBQIJjVROOH45FGFMz+K198g1QdPm2Dyg2jFlP73FEabyZOVqMBlIr9JN24MbcOLnyFIkfkosf/ySnTQa1NpAyXPz5izOMN7ig89tt2hi1XcW1YHkU3y0CB3AAZGEtJ6oqL6GTyw35OIDW3laJTrh2d5OzuPZGC00Wc+s9+MAJdO5kKwTKV+V4Fn03F1sHsJ4uQhcHbDNC6TZyOb+XMOLQYRdh9cBQ3oil+upclUmoE7A+ibZa4Aoaj6d4="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-ci-setup-feedstock/master/recipe/conda_forge_ci_setup/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root

      conda install -n root -c conda-forge --quiet --yes conda-forge-ci-setup=2 conda-build
      setup_conda_rc ./ ./recipe ./.ci_support/${CONFIG}.yaml

      source run_conda_forge_build_setup

    # compiler cleanup
    - |
      mangle_compiler ./ ./recipe ./.ci_support/${CONFIG}.yaml

script:
  # generate the build number clobber
  - make_build_number ./ ./recipe ./.ci_support/${CONFIG}.yaml
  -  conda build ./recipe -m ./.ci_support/${CONFIG}.yaml --clobber-file ./.ci_support/clobber_${CONFIG}.yaml
  - upload_package ./ ./recipe ./.ci_support/${CONFIG}.yaml