travis:
  secure:
    BINSTAR_TOKEN: dtlfENtUb/suPJIKZxilT7CwncFXbo7v1ffk3MAmz0M8BE4hAgKTMripIu2ccePDWJF4BQOkmVb276KVHb39rk7UUdsfKdvyPwq8GEJAuNfXcRQnKf5zXHA86wSuNTE2fGNhwkJJE9wT+HBE6WeEGGsK8qezOyycp+N1Ztr9ziG9K8YS7/VhRdCqe5pcMDG9jGJOgoZZuRr9K8VIaRTgODPMu1H5Uyz1KeZtfW0GBusiOr7R0ZnNYqbjkSOB2GG98aTchnDAllqdzoYB1pVn7v4bSUvKG8scEdFJVbnsLKjQYhRSrRBLBS5QlNK68DWoHkSrnLOE7zRmKqhhxz54FDSQ1Hp+zQ2Dij9FtjRQOecZrycZznhaPFIeFNti4eRBpfaM4eajhPm5DQO6FeJChib5+UnYsvasaJYxM45vR726Z3KvtIT2so0Gh6xXRnkoBBDceoZqST+D8K7WHUlCBGJ/gelvv0I6CmijKsjrN4DHT5iyJoL5diOO2cs+HArPRU1LXsiPttw3yQ4XtuO+EU15KK2MV3xCKgS9NHzFfyME1jhaYw0jE4q+Z8e601ZKlqblziuIbI0EykSK72XkhFG2WKxZVvoOD2SXfbMfNVlkqCRbrgGE6RNEgavYSiDFP7IIDhx0UbYu8qwU7Bay5HvlDhD1t1W8y0j3W5SKhTM=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
max_py_ver: '37'
